### ISSUE TITLE
Blocks with no language have no copy button

### ISSUE THREAD

**Issue by NomarCub** [nothingislost/obsidian-codemirror-options#12]
The [Code Copy plugin](https://github.com/superDuperCyberTechno/obsidian-code-copy) is also prevented from placing a button on most of these when this plugin's feature is enabled.

Originally mentioned in https://github.com/nothingislost/obsidian-codemirror-options/issues/5.

**Comment by nothingislost** [comment]
All three of these issues should be addressed in the latest release. Let me know your thoughts when you get a chance to test.

**Comment by NomarCub** [comment]
Thanks!
I tested them. I closed two, and left the newline one open, see my reason there.
