### ISSUE TITLE
Fail to open pages - Cannot read property 'length' undefined. 

### ISSUE THREAD

**Issue by joelkmurray** [nothingislost/obsidian-codemirror-options#13]
Hi NothingIsLost, 

Amazing plugin, thank you for creating it for the community.

I have an issue where opening links with hide tokens enabled causing Obsidian to fail to open the page.

Fires the error - Cannot open xxx.md. Cannot read property 

Replication:
- This occurs cross-machine, windows 11 and 10. 
- Occurs cross-vault
- The issue is intermittent, only occurring in 1 in 5-ish attempts to open a file
- Occurs when navigating to 'rich' files with complex content and simple one line text notes.
- Happens MUCH more often when leaving complex files. I cant narrow it down further but large, multi-section files seem to trigger the error 50%+ of the time. Still intermittent.

Testing:
- Occurs with only CodeMirror enabled (including disabling all core plugins as well)
- Occurs with only token enabled in CodeMirror
- Quick websearch connects it to 'calling the var before its created' if that's any help at all.

Image:
![image](https://user-images.githubusercontent.com/43304806/133908409-103886d6-3a8e-45c0-bf3a-2dcd837758bb.png)

Thank you again,
J

**Comment by nothingislost** [comment]
Thanks for the report. I've seen this as well and it's a tough one to resolve. I have the issue pinpointed but all of the fixes I've attempted have negatively impacting the functionality of hide tokens so far. I'll update this issue once I have a workable solution.

**Comment by nothingislost** [comment]
This should be resolved in the latest release, 0.1.4.
