### ISSUE TITLE
Mermaid codeblocks not rendering

### ISSUE THREAD

**Issue by frvkl** [nothingislost/obsidian-codemirror-options#14]
When adding a mermaid graph using the following block identifier ```mermaid```:

```mermaid
gantt
    title  
    dateFormat  DD-MM-YY
	axisFormat	%d %b
	section Valideren in S1
	Rel_3/16:   rel_3.16,    05-07-21, 23-07-21
	Release 01 (version upgrade): rel_2011_01, 26-07-21, 03-09-21
	Release 02: rel_2011_02, 06-09-21, 24-09-21
	Release 03: rel_2011.03, 27-09-21, 15-10-21
	Release 04: rel_2011.04, 18-10-21, 05-11-21
	Release 05: rel_2011.05, 08-11-21, 26-11-21
	Release 06: rel_2011.06, 29-11-21, 17-12-21	
```

This plugin is blocking the rendering of the mermaid graph. Is it possible to exclude certain codeblocks?

**Comment by nothingislost** [comment]
Hmm, I see this in preview mode with that code block. What does it look like for you?

![image](https://user-images.githubusercontent.com/89109712/134026843-7c23da1d-49cf-43e9-953c-2b7964d1c253.png)
