### ISSUE TITLE
Hide link addresses, only show titles?

### ISSUE THREAD

**Issue by loopernow** [nothingislost/obsidian-codemirror-options#20]
Thank you for this plugin! I'm not sure if it's within the scope of this project, but would it be possible to hide link addresses when they have titles? For instance, in a link like [[2021-09-29|today]], would it possible to hide not only the "[[]]", but also the "2021-09-29" and the "|" and only show "today"?

**Comment by nothingislost** [comment]
Something like this?
![2021-09-29 20 53 37](https://user-images.githubusercontent.com/89109712/135384461-d7ef0bdd-9dfc-4b0d-b87b-12221668de50.gif)

That's something I'm working on bringing over from HyperMD. Should be in a future release once I have it stable.

**Comment by loopernow** [comment]
Yes, exactly, looks great! :)

**Comment by nothingislost** [comment]
The latest pre-release  https://github.com/nothingislost/obsidian-codemirror-options/releases/tag/0.2.0 includes this functionality. 

It still needs testing so you'll need to download and install the release manually or use https://github.com/TfTHacker/obsidian42-brat and add the repository "nothingislost/obsidian-codemirror-options"

**Comment by Obadiahcruz** [comment]
https://user-images.githubusercontent.com/22825246/135802096-c3851b8e-f036-4ec5-bb83-c7165d200a35.mov

Im getting this issue with the new release, also, how do we hide external links when using ![test]

https://user-images.githubusercontent.com/22825246/135802156-22b70658-8a7a-4a17-b014-8e82377038aa.mov

**Comment by nothingislost** [comment]
Are you using OpenMD mode there? I'd need more detail around what exactly is making that text transparent as it's not my plugin doing that. You may want to test in a new vault to remove any variables.

Support for ![]() isn't there yet but I can look at adding it. Please raise a new issue specifically for that feature.

**Comment by Obadiahcruz** [comment]
i dont know what happened but it was resolved with the community store plugin download 2.1 lol 

support for ```! [ ] ()``` would be great!
