### ISSUE TITLE
Pre-release 0.07 WYSIWYG bold, italic, monospace cannot be rendered

### ISSUE THREAD

**Issue by ArmandXiao** [nothingislost/obsidian-codemirror-options#3]
![Imgur](https://i.imgur.com/ZwEEN3U.png)

Proper rendered (Successfully hide markdown)
- Headers
- Quotes
- Internal Link / Backlink

Not rendered (Cannot hide markdown)
- both syntax (`**bold**` or `__bold__`)
- both syntax (`*italic*` or `_italic_`) 
- `mono space`

I know it's still under development; I have been expecting this feature for a long time, and I truly hope bold, italic, and monospace can be implemented. 👍 😄

**Comment by nothingislost** [comment]
@ArmandXiao the elements you referenced are indeed supported. You may have a theme, plugin, or snippet overriding the styling of those elements.

You can verify that the plugin is working by inspecting a bold or italic string (on an inactive line) and checking for the .hmd-hidden-token class:

![image](https://user-images.githubusercontent.com/89109712/132238074-df7c4c93-cbcb-4f1a-9360-dd6ebbf844d7.png)

If the class is there, you'll want for any styling which may be overriding the hiding rules:

![image](https://user-images.githubusercontent.com/89109712/132238180-438ba293-d375-40d9-bf1b-0fd8191a96a6.png)

**Comment by quangnd159** [comment]
Just want to chime in that the plugin doesn't render bold, italic, and monospace for me as well.

I disabled all plugins except the CodeMirror Options, turned off all snippets, and used the default themes. Still, only headings and links work.

**Comment by quangnd159** [comment]
I found the problem. It's the Templater plugin, specifically the Syntax Highlighting toggle. Just toggle it off and restart Obsidian and CodeMirror Options' WYSIWYG works perfectly. 
Thanks for your great plugin!

**Comment by ArmandXiao** [comment]
@nothingislost @quangnd159 Your time is greatly appreciated!! Thank you.
- The problem is indeed from `Syntax Highlighting toggle` option in **Templater** Plugin for me also.

**Again thanks for this great feature and plugin!**

---

![image](https://user-images.githubusercontent.com/45375764/132246253-8f7ba1b6-a24c-440e-9355-75c55a687c93.png)

**Comment by nothingislost** [comment]
Thanks for helping debug the issue. I'll make sure to add the templater setting incompatibility issue in the readme.
