### ISSUE TITLE
Render <mark> ?

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-codemirror-options#33]
Is it possible to render the mark tag? Just trying out Chetachis new highlighter plugin ☺️

![image](https://user-images.githubusercontent.com/46250921/137360644-d1c62676-7da9-496e-b3c5-3f43d9d3b09f.png)

**Comment by nothingislost** [comment]
This one might be tricky but I like the idea. I'll see what I can do. Thanks for the suggestion.

**Comment by nothingislost** [comment]
Actually, HyperMD has a fold-html plugin which I haven't implemented yet but it could do something like this.
![2021-10-14 10 01 10](https://user-images.githubusercontent.com/89109712/137363352-10e4ad88-966a-4b30-b076-ac788cf247be.gif)

**Comment by chetachiezikeuzor** [comment]
Woah, I didn't think that was possible but this looks fantastic! Do let me know if you need anything 💪🏽

**Comment by nothingislost** [comment]
Even better, select the full highlighted text on expand so that it can be unhighlighted
![2021-10-14 15 24 45](https://user-images.githubusercontent.com/89109712/137403952-63ce4c1e-1d4f-4675-8cf0-b4dcc49fbb17.gif)

**Comment by chetachiezikeuzor** [comment]
Out of curiosity, how would this work with `<img>` tags, or any other tag for that matter? Could this also be used to render an image or iframe from their corresponding tags? I know Ozan's Image in Editor plugin renders iframe, though it hasn't worked for me unfortunately.
