### ISSUE TITLE
Feature Request: A way to disable LateX mode.

### ISSUE THREAD

**Issue by chrisirhc** [nothingislost/obsidian-codemirror-options#38]
When using 2 `$` symbols within a sentence, looks like HyperMD thinks this is inline LateX:
![image](https://user-images.githubusercontent.com/132584/137650101-162f7e24-13aa-4fdd-93df-e068ae4d79ae.png)

May I request a way to disable this behavior?

**Comment by nothingislost** [comment]
Ah, you're right. I'll get that fixed in the next release.

**Comment by nothingislost** [comment]
This may not be the best issue to jump into as it involves modifying the markdown parser logic. If you're interested in how it works, the current logic starts here https://github.com/nothingislost/obsidian-codemirror-options/blob/4a99ef43eabcfbd75b36a0a18694c5070cc33aa4/src/hmd-mode.js#L324

I believe the regex on this line needs tuning https://github.com/nothingislost/obsidian-codemirror-options/blob/4a99ef43eabcfbd75b36a0a18694c5070cc33aa4/src/hmd-mode.js#L327
