### ISSUE TITLE
[BUG] Repeat Rendering

### ISSUE THREAD

**Issue by Borber** [nothingislost/obsidian-codemirror-options#51]
![image](https://user-images.githubusercontent.com/30563826/138932703-4981d3bb-d2f0-46b6-b59d-3f5db0b295cd.png)

I don't know why, but the plugin occasionally renders two identical ones

Source Code `<p class="separator">2021-10-27</p>`

**Comment by nothingislost** [comment]
I'm still seeing this happening when switching between certain files with HTML block elements. I'll reopen this until I can track it down.

**Comment by nothingislost** [comment]
I believe this is sorted out for good now.
