### ISSUE TITLE
[Feature Request] Add support for Buttons plugin

### ISSUE THREAD

**Issue by Aaron-Bopp** [nothingislost/obsidian-codemirror-options#58]
Would love support for inline and codeblock [buttons](https://github.com/shabegom/buttons). Thanks for everything you do!

**Comment by imeed166** [comment]
me too

**Comment by nothingislost** [comment]
The buttons plugin doesn't currently expose the needed methods to render buttons in edit mode. You can try and work around that by embedding button blocks inside of an admonition block. That will get them to render but I'm not sure they will behave properly when used that way.

**Comment by imeed166** [comment]
Tried inline buttons with admonition, didn't work, it just displayed the text.

**Comment by imeed166** [comment]
It works with the new update (0.7.0), thank you.
