### ISSUE TITLE
Syntax highlight default font size

### ISSUE THREAD

**Issue by NomarCub** [nothingislost/obsidian-codemirror-options#6]
The syntax highlight feature makes code block font sizes bigger than the default in Obsidian (16px).
I saw the Style Settings plugin recommended to remedy this, but I'd rather not install another plugin for only this purpose, especially with the default being 16px to begin with.

**Comment by nothingislost** [comment]
Fair enough. I'll set it to 16px shortly. I would highly recommend Style Settings though as it will allow you to pick syntax highlighting themes and it's pretty common for themes and addons to include customization via Style Settings.

**Comment by nothingislost** [comment]
Resolved in 0.1.0
