### ISSUE TITLE
[Feature Request]: Render Better PDF plugin code elements

### ISSUE THREAD

**Issue by infinityiowastaken** [nothingislost/obsidian-codemirror-options#60]
Plugin available [here](https://github.com/MSzturc/obsidian-better-pdf-plugin)

**Comment by nothingislost** [comment]
The plugin author of Better PDF would need to update their plugin to expose the post processor method. I can't currently get to it to render these in edit mode.

**Comment by nothingislost** [comment]
In the latest version, you can workaround this by embedding a Better PDF block inside of an Admonition like this:
`````
````ad-info
collapse: open
```pdf
{"url": "MyPDF.pdf"}
```
````
`````

**Comment by infinityiowastaken** [comment]
Thank you for the workaround!
