### ISSUE TITLE
The text entered will inexplicably disappear. Appears from time to time to show a notification that the file has been automatically merged.

### ISSUE THREAD

**Issue by zhl111** [nothingislost/obsidian-codemirror-options#61]
![image](https://user-images.githubusercontent.com/29135984/139690343-602dadc7-f8b2-4eb1-a03f-3f98a22e8057.png)

**Comment by nothingislost** [comment]
That console log data isn't related to CodeMirror Options. It appears to come from the https://github.com/Aidurber/obsidian-plugin-dynamic-toc plugin
https://github.com/Aidurber/obsidian-plugin-dynamic-toc/blob/0a1b73eec98891155feb177dd644a661b234670e/src/utils/timer.ts#L15

**Comment by zhl111** [comment]
Yes. But the interesting thing is that as mentioned, turning off the plugin CodeMirror, restarting the obsidian software，console no longer displayed and problem disappeared
