### ISSUE TITLE
[Feature Request] Render [TOC] in edit mode

### ISSUE THREAD

**Issue by Quorafind** [nothingislost/obsidian-codemirror-options#63]
Is it possible to render [TOC] through https://github.com/aidurber/obsidian-plugin-dynamic-toc ?

**Comment by nothingislost** [comment]
The TOC plugin author would need to update their plugin to expose the post processor method. I can't currently get to it in order to render TOC blocks.

**Comment by nothingislost** [comment]
You can kind of do this in the latest version 0.7 by embedding TOC inside of an admonition like this:
`````
````ad-info
```toc
    style: bullet | number (default: bullet)
    min_depth: number (default: 2)
    max_depth: number (default: 6)
```
````
`````
