### ISSUE TITLE
embeds not working?

### ISSUE THREAD

**Issue by rmchale** [nothingislost/obsidian-codemirror-options#65]
This should embed the note, but seems to be rending the link. 
```
![[link-to-note]]
```

**Comment by nothingislost** [comment]
This plugin does not currently render embeds in edit mode. You can check out Ozan's Image in Editor plugin for that functionality.

**Comment by nothingislost** [comment]
I take it back. Embeds are now supported in the latest 0.8.2 release :)

**Comment by rmchale** [comment]
do I have to do anything to enable?  What do the caution signs mean?  I am not seeing embeds
<img width="346" alt="Screen Shot 2021-11-08 at 7 50 44 PM" src="https://user-images.githubusercontent.com/265698/140846998-d162e8cc-f66e-493a-b8b7-6cf0d2ee5458.png">

**Comment by rmchale** [comment]
Restarting obsidian seemed to fix
