### ISSUE TITLE
[Bug] : flickering problem

### ISSUE THREAD

**Issue by imeed166** [nothingislost/obsidian-codemirror-options#67]
There is a problem with the cursor when rendering admonition with inline buttons.

https://user-images.githubusercontent.com/38974541/140332142-5d312234-6465-4356-b01b-ccb80d01d935.mov

**Comment by nothingislost** [comment]
Interesting. I can't seem to replicate this. can you provide the source for that code block?

**Comment by imeed166** [comment]
In the admonition, it's `` `button-later` ``
and the original button is like this ~
````
```button
name later
type line(3) text
action state: ⬜
replace [3,3]
```
^button-later
````

**Comment by nothingislost** [comment]
Unfortunately, I can't seem to replicate this. Does it do this for you on the default theme with all other plugins disabled?

![Uploading 2021-11-05 16.17.50.gif…]()

**Comment by imeed166** [comment]
I disabled everything except for admonition, buttons and code mirror with the default theme. Still the same result


https://user-images.githubusercontent.com/38974541/140599145-0da8aad7-37b5-4092-a4e5-09be59afd9fb.mov

**Comment by imeed166** [comment]
I don't have this issue anymore with the new update (0.8.2)
