### ISSUE TITLE
Can't get front matter CSS to work

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-codemirror-options#69]
I might be misunderstanding the instructions. 

1. I put this in the front matter
```
---
text-color: pink
--- 
```

2. Then added this to the front matter key section

![image](https://user-images.githubusercontent.com/46250921/140374844-6f2c0000-bef4-4194-a85a-1801ed6dd8cd.png)

3. Then I expected the text of the page to turn pink but it doesn't

Am I missing a step?

**Comment by nothingislost** [comment]
Yeah, you need to create a snippet that does something with that variable now.  In the demo video, I have a CSS snippet which is applying this style:

```css
.CodeMirror-line {
 color: var(--text-color);
}
```

you may need to add !important to the color declaration if it still isn't working.
