### ISSUE TITLE
Some languages are not always recognized

### ISSUE THREAD

**Issue by NomarCub** [nothingislost/obsidian-codemirror-options#7]
JSON, HTML and JavaScript code blocks didn't work right in the Obsidian Help vault. I only installed CodeMirror Options, Editor Syntax Highlight, and have only the syntax highlight feature enabled. Sometimes they worked right, but most of the time they didn't. I used the reload command and used this regex - `/```[^\s]/` - to jump around between code blocks in different notes in the vault.
I'm on Windows 10, and used the latest versions of Obsidian and the plugins.

![image](https://user-images.githubusercontent.com/5298006/132940724-fce4393d-c41b-400b-89fc-481188f1b31e.png)

![image](https://user-images.githubusercontent.com/5298006/132940739-b938c447-3344-4f60-9392-91d4aa83a6b4.png)

![image](https://user-images.githubusercontent.com/5298006/132940930-3661a000-74d3-4091-a6b9-780149fb2a95.png)

**Comment by nothingislost** [comment]
Should be addressed in 0.1.1
