### ISSUE TITLE
[Bug]Clicking on backlinks in the bottom of a page does not open the link

### ISSUE THREAD

**Issue by gavinmn** [nothingislost/obsidian-codemirror-options#74]
I'm noticing that clicking on backlinks embedded in the bottom of a page only works if they are near the top of the list. I haven't really be able to narrow down the cause further, but trying to open a backlink that is more than ~> 5 links down, trying to link unlinked mentions, trying to show and hide unlinked mentions all just jump the cursor to the last line in the document.

**Comment by gavinmn** [comment]
I was able to narrow this down actually - the error occurs when you try and click on a link that you have to scroll down to see. Adjusting the size of the window affects it.

**Comment by nothingislost** [comment]
This was resolved a couple releases ago.
