### ISSUE TITLE
How to set up to see “ the <CODE> and <HTML> buttons”

### ISSUE THREAD

**Issue by traymi** [nothingislost/obsidian-codemirror-options#76]
How to set up to see “ the 'CODE' and 'HTML' buttons” ？ I have opened all the settings in CodeMirror Options，And did not see any button display at the bottom ( I use is [Blue topaz] theme ) . Did I set something wrong?

![set](https://user-images.githubusercontent.com/37623123/140783340-e937c372-621e-4660-bff3-9bfb7415c305.jpg)

![button](https://user-images.githubusercontent.com/37623123/140783344-2f1fdd0d-72f7-472d-ab4a-c0eff05bd14b.jpg)

**Comment by traymi** [comment]
Do you support mermaid ? how to set mermaid ?
![mermaid](https://user-images.githubusercontent.com/37623123/140785415-9b274e93-7052-4b44-9276-80c3e66f7b2a.jpg)

**Comment by nothingislost** [comment]
Oh, sorry about that. Those buttons aren't from my plugin. I set those up using the cMenu plugin which allows you to map commands to icons.

Mermaid is not currently supported natively but you can wrap your mermaid chart in an admonition (assuming you use the admonition plugin) as a work around like this:
`````
````ad-info
```mermaid
<mermaid code goes here>
```
````
`````

**Comment by traymi** [comment]
Thank you for solving my problem. Thank you so much
