### ISSUE TITLE
Font size doesn't scale

### ISSUE THREAD

**Issue by NomarCub** [nothingislost/obsidian-codemirror-options#8]
Default:
![default](https://user-images.githubusercontent.com/5298006/132941186-bdee41e0-5709-4bd1-b32a-cc0d00874ec7.gif)

Plugin:
![plugin](https://user-images.githubusercontent.com/5298006/132941189-68abdb77-e4ea-4ea3-985f-65b4506841df.gif)

**Comment by nothingislost** [comment]
Should be addressed in 0.1.1
