### ISSUE TITLE
[Q&A] I want to change the click event of this element

### ISSUE THREAD

**Issue by Borber** [nothingislost/obsidian-codemirror-options#82]
![image](https://user-images.githubusercontent.com/30563826/141739711-ffef60d7-6c2f-4fdc-b959-0424de25bf0c.png)

I noticed that the checkboxes in the edit screen also support click toggle after codemirror is enabled, I want to change the click event (I want to add more checkboxes), how should I do it? Thanks in advance for your advice!

**Comment by nothingislost** [comment]
Hi Borber, currently that click handler is hard coded within this file https://github.com/nothingislost/obsidian-codemirror-options/blob/main/src/hmd-click.js

It's on the roadmap to make that handler more extensible but, in the mean time, if you're interested in creating a PR to add additional click functionality I'd be happy to review it.
