### ISSUE TITLE
[Bug] Inline latex renders as block latex

### ISSUE THREAD

**Issue by y9san9** [nothingislost/obsidian-codemirror-options#93]
There are some differences between how latex is rendered in preview mode and how latex is rendered in editor. I guess that is because even in in editor mode you render inline latex as block latex. 

I think so, because according to specification integral in inline mode should be rendered like this: <img width="147" alt="Снимок экрана 2021-11-24 в 15 44 25" src="https://user-images.githubusercontent.com/46930374/143242396-8bb1242a-8833-4d2e-99f0-8ee1f87bf271.png"> and in block mode like this: <img width="150" alt="Снимок экрана 2021-11-24 в 16 00 09" src="https://user-images.githubusercontent.com/46930374/143243144-e906983c-d0e1-48c8-94c1-be4b5a474a7e.png"> (it is taller comparing to `f(x)`)

But while using this plugin latex always renders like this: <img width="161" alt="Снимок экрана 2021-11-24 в 15 44 19" src="https://user-images.githubusercontent.com/46930374/143243326-815afb03-f545-4333-835d-b09291aa6478.png">. It looks more like the second variant (except the braces, but it is just a different symbols, nevermind)

So, please, could you fix this issue and render different latex depending on math type (inline or block). 
By the way, your plugin is awesome! I use it only for math, since other cases didn't found convenient **FOR ME**, and since I'm studying in a university the plugin helps me a lot!

**Comment by nothingislost** [comment]
hmm, I thought I sorted this out in #48 but I guess there's styling differences I'm not accounting for as well. Could you provide me with the actual latex text to I can use it as a test case?

**Comment by y9san9** [comment]
Yep, you can use one of such "tags": \int, \lim, \sum. They all look different in $inline math$ and in $$block math$$.
But in my case it is `\int^a_b f(x)`

**Comment by y9san9** [comment]
Maybe this will be useful to you.

![Screenshot_20211125_043013](https://user-images.githubusercontent.com/46930374/143348607-46f80e47-a8b9-49c4-bd61-664b14dd3589.jpg)

**Comment by nothingislost** [comment]
Thanks for the input. I'll have this fixed in the next release.

For the Math Preview window, do you think it should always show the block representation or would you want your inline math to preview as inline?

**Comment by y9san9** [comment]
I think there is no problem if always to show a block math there. The only problem I had that after switching to preview mode, I don't see the exact math that was in editor mode. This also causes scroll bugs sometimes, since heights of lines are different.

**Comment by y9san9** [comment]
Thanks for your time, you do awesome job 🔥

**Comment by nothingislost** [comment]
Sounds good! It should work like this after I push the next update in a bit
![image](https://user-images.githubusercontent.com/89109712/143480602-fd2c6f5f-77b6-47cf-81c3-0bd8bb0195ea.png)

**Comment by nothingislost** [comment]
Should be fixed in v0.9.4

**Comment by y9san9** [comment]
Works fine, thanks
