### ISSUE TITLE
Readme theme/font

### ISSUE THREAD

**Issue by ZibraMax** [nothingislost/obsidian-codemirror-options#94]
I love your plugin!

I would appreciate if you could tell me the font name/theme that you are using in this image:

![](https://user-images.githubusercontent.com/89109712/139353797-4e9bdd1c-52ea-417e-89a4-7311b04c0a55.gif)

Thanks!

**Comment by nothingislost** [comment]
Hello! That font is the Google font, Quicksand.

**Comment by ZibraMax** [comment]
THANKS!!!!
